routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/projects/create', 'ProjectController@create')->name('projects.create');

Route::middleware('auth')->group(function() {

    Route::resource('projects', 'ProjectController');

    Route::post('/projects/{project}/tasks', 'ProjectTasksController@store')->name('tasks.store');

    Route::post('/invitations/{project}', 'ProjectInvitationsController@store')->name('invitations.store');

	Route::patch('/projects/{project}/tasks/{task}', 'ProjectTasksController@update')->name('tasks.update');
});

resources/views/partials/card.blade.php
<div class="card">
    <div class="border-l-4 border-blue-300 -ml-5 py-3">
        <a class="font-normal text-xl py-4 ml-6" href="{{ route('projects.show', $project->id) }}">
            {{ Str::limit($project->title, 10) }}
        </a>
    </div>
    <div class="text-gray-400 py-5">{{ Str::limit($project->description, 100)}}</div>
    @can('manage', $project)
        <div class="text-right">
            <form action="{{ route('projects.destroy', $project) }}" method="post">
                @csrf
                @method('delete')
                <button type="submit" class="bg-red-600 py-2 px-6 font-bold text-white rounded">Delete</button>
            </form>
        </div>
    @endcan
</div>

resources/views/partials/form.blade.php
@csrf
<div class="flex flex-col space-y-3">
    <label for="title" class="text-lg font-medium">Title</label>
    <input type="text"
           value="{{ $project->title }}"
           name="title"
           class="border border-gray-300 rounded py-2 focus:outline-none focus:ring-2
           focus:ring-blue-400 focus:border-transparent @error('title') border-red-300 @enderror"
           required autocomplete="title">
    @error('title')
    <span class="text-red-500 mt-4" role="alert">
        <strong>{{ $message }}</strong>
    </span>
    @enderror
</div>
<div class="flex flex-col space-y-3">
    <label for="description" class="text-lg font-medium mt-3">Description</label>
    <textarea name="description"
              class="border h-24 border-gray-300 rounded py-2 focus:outline-none
              focus:ring-2 focus:ring-blue-400 focus:border-transparent @error('description') border-red-300 @enderror"
    >{{ $project->description }}</textarea>
</div>
@error('description')
<span class="text-red-500 mt-4" role="alert">
        <strong>{{ $message }}</strong>
</span>
@enderror
<div class="flex mt-6 justify-between items-center">
    <button type="submit" class="bg-blue-400 rounded-lg py-3 px-4 text-white mr-2">
        {{ $buttonText }}
    </button>
    <a href="{{ route('projects.index') }}">Cancel</a>
</div>

resources/views/partials/invitations.blade.php
<div class="card mt-6">
    <div class="border-l-4 border-blue-300 -ml-5 py-3">
        <p class="font-normal text-xl py-4 ml-6">
            Invite User
        </p>
    </div>
    <div class="text-right">
        <form action="{{ $project->path() . '/invitations' }}" method="post" class="mt-4">
            @csrf
            <input type="text"
                   name="email"
                   class="border border-gray-300 rounded py-2 w-full pl-6
                                   focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent @error('email') border-red-300 @enderror"
                   autocomplete="email"
                   placeholder="Enter email address"
            >
            <button type="submit" class="bg-blue-400 mt-4 py-2 px-6 font-bold text-white rounded">Invite</button>
        </form>

        @if ($errors->invitations->any())
            <div class="text-red-500 mt-5">
                <ul>
                    @foreach ($errors->invitations->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
</div>