routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/projects/create', 'ProjectController@create')->name('projects.create');

Route::middleware('auth')->group(function() {

    Route::resource('projects', 'ProjectController');

    Route::post('/projects/{project}/tasks', 'ProjectTasksController@store')->name('tasks.store');

    Route::post('/invitations/{project}', 'ProjectInvitationsController@store')->name('invitations.store');

	Route::patch('/projects/{project}/tasks/{task}', 'ProjectTasksController@update')->name('tasks.update');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
   /**
   * This is an example of code quality, there is some refacotoring and extration to a trait for code usability 
   **/
    use RecordsActivity;

    protected $guarded = [];

    public function path()
    {
    	return "/projects/{$this->id}";
    }

    public function owner(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
    	return $this->belongsTo(User::class);
    }

    public function tasks(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
    	return $this->hasMany(Task::class);
    }

    public function addTask($body): Model
    {
        return $this->tasks()->create([
                'user_id' => auth()->id(),
                'body' => $body
            ]
        );
    }

    public function activity(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Activity::class)->latest();
    }

    public function invite(User $user) : void
    {
        $this->members()->attach($user);
    }

    public function members(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Redirect;
use Inertia\Inertia;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Project $project
     * @return \Inertia\Response
     */
    public function index(Project $project)
    {
        return Inertia::render('Project/Index', [
            'projects' => auth()->user()->accessibleProjects()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Project $project
     * @return View|\Inertia\Response
     */
    public function create(Project $project)
    {
        return inertia('Project/Create', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $attributes = request()->validate([
            'title' => 'required',
            'description' => 'required',
            'notes' => 'min:3'
        ]);

        $project = auth()->user()->projects()->create($attributes);

        return redirect($project->path());
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Project $project
     * @return \Inertia\Response
     */
    public function show(Project $project)
    {
        $this->authorize('update', $project);

        return Inertia::render('Project/Show', [
            'project' => $project,
            'activities' => $project->activity->load('subject', 'user'),
            'project_tasks' => $project->tasks,
            'can' => auth()->user()->can('manage', $project),
            'status' =>  request()->session()->get('error'),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Project $project
     * @return \Illuminate\View\View|\Inertia\Response|\Inertia\ResponseFactory
     */
    public function edit(Project $project)
    {
        return inertia('Project/Edit', [
            'project' => $project,
            'status' => request()->session()->get('error')
        ]);
    }


    public function update(Project $project)
    {
        $this->authorize('update', $project);

        $attributes = request()->validate([
            'title' => 'sometimes|required',
            'description' => 'sometimes|required',
            'notes' => 'sometimes'
        ]);

        $project->update($attributes);

        return Redirect::route('projects.show', $project);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Project $project
     * * @return \Illuminate\Routing\Redirector
     */
    public function destroy(Project $project)
    {
        $this->authorize('manage', $project);

        $project->delete();

        return Redirect::route('projects.index');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container w-1/2 mx-auto mt-5">
        <div class="card py-8">
            <h3 class="py-6 text-2xl text-center">Let Create Something New</h3>
            <form action="/projects" method="post">
                @include('partials.form', ['buttonText' => 'Add Project'])
            </form>
        </div>
    </div>

@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container w-1/2 mx-auto mt-5">
        <div class="card py-8">
            <h3 class="py-6 text-2xl text-center">Edit the Project</h3>
            <form action="{{ route('projects.update', $project) }}" method="post">
                @method('PATCH')
                @include('partials.form', ['buttonText' => 'Update Project'])
            </form>
        </div>
    </div>

@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="flex justify-between items-end mb-3 py-6 ">
        <h3 class="text-gray-500">My Projects</h3>
        <a href="{{ route('projects.create') }}" class="bg-blue-400 py-3 px-6 rounded-lg text-white">Add Project</a>
    </div>
    <div class="grid grid-cols-1 md:grid md:grid-cols-2 lg:grid lg:grid-cols-3 gap-4">
        @forelse ($projects as $project)
            @include('partials.card')
        @empty
            <div>You don't have projects yet</div>
        @endforelse
    </div>

@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')

    <header>
        <div class="flex justify-between items-center py-4">
            <h3 class="text-gray-400 font-normal pr-4"><a href="{{ route('projects.index') }}">My Projects</a>
                / {{ $project->title}} </h3>
            <a href="{{ route('projects.edit', $project) }}" class="button">Edit Task</a>
        </div>
    </header>

    <main>
        <div class="flex">
            <div class="w-3/4 mr-8">
                @foreach ($project->tasks as $task)
                    <form action="{{ $project->path() .'/tasks/' . $task->id }}" method="post" class="card mb-3">
                        @method('PATCH')
                        @csrf
                        <div class="flex items-center">
                            <input type="text" name="body" class="w-full {{ $task->completed ? 'text-gray-300' : '' }}"
                                   value="{{ $task->body }}">
                            <input type="checkbox" name="completed"
                                   onChange="this.form.submit()" {{ $task->completed ? 'checked' : '' }}>
                        </div>
                    </form>
                @endforeach
                <form action="{{ route('tasks.store', $project->id) }}" method="post">
                    @csrf
                    <input class="card mb-3 w-full py-4" placeholder="Begin to add task ...." name="body">
                </form>

                <h3 class="text-gray-400 font-normal pr-4 mt-6 mb-3">General Notes </h3>
                <form action="{{ route('projects.update', $project) }}" method="post">
                    @csrf
                    @method('PATCH')
                    <textarea class="card mb-3 w-full h-64" placeholder="Have additional notes ?"
                              name="notes">{{ $project->notes }}</textarea>
                    <button class="button" type="submit">
                        Add Notes
                    </button>
                </form>
                @error('notes')
                <span class="text-red-500 mt-6" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <div class="w-1/4">
                @include('partials.card')
                @include('activity.card')
                @can('manage', $project)
                    @include('partials.invitations')
                @endcan
            </div>
        </div>
    </main>
@endsection